global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "sentinelx-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["sentinelx-worker-v1:8001", "sentinelx-worker-v1_1:8001", "gateway:8000"]

  - job_name: sentinelx-worker
    metrics_path: /metrics
    static_configs:
      - targets: ["sentinelx-worker-v1:8001", "sentinelx-worker-v1_1:8001"]

